### ISSUE TITLE
Int 21h function 00h detection broken?

### ISSUE THREAD

**Issue by ecm-pushbx** [karcherm/xtize#2]
Browsing the sources I noticed that the detection of int 21h function 00h seems to be broken. It checks AL rather than AH:

https://github.com/karcherm/xtize/blob/7dd0e0f48da5ad497b98f2efb2473f7d62b252eb/enter.asm#L312

**Comment by karcherm** [comment]
Thanks for your issue report. You are correct. This bug is fixed in current master.
